### PR TITLE
Incorporate in-browser communication security considerations

### PR DESCRIPTION
**Pull request by iphoneintosh**
Hi,

We would like to request the inclusion of _in-browser communication security considerations_ in the BCP. As the paper "DISTINCT: Identity Theft using In-Browser Communications in Dual-Window Single Sign-On" shows, in-browser communications like the [postMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) are widely used by Clients and Authorization Servers as an alternative to HTTP redirects. In some cases, they are used insecurely, leading to OAuth tokens leaks and injections. The paper will be published soon at ACM CCS in November 2022 and is accessible [here](https://distinct-sso.com/paper.pdf). This is a joint work with @mladevbb, @CheariX, and @joergschwenk.

We think that the paragraph added in this pull request helps developers in understanding the risks and best practices of using in-browser communications in OAuth. Please do not hesitate to ask further questions or provide feedback. We will be happy to answer and discuss them.

Best,
Louis

/cc @CheariX @mladevbb

### CODE REVIEW

**Comment by danielfett** [comment]
Please feel free to add the names of those who provided this PR to the contributors section (if not already there).

**Comment by iphoneintosh** [comment]
Thanks, I just added the names and combined all commits into a single commit to increase clarity.

**Comment by panva** [comment]
I believe it would be worthwhile to link to an example mechanism that relies on postMessage to deliver responses.

This would be https://datatracker.ietf.org/doc/html/draft-sakimura-oauth-wmrm-00. This also makes use validated uris/origins passed to postMessage and its code examples take care of verifying the event origin to be the AS on the client side.

**Comment by CheariX** [comment]
@panva Do we really want to link to an expired draft?

**Comment by panva** [comment]
The BCP already does, search for I-D.bradley-oauth-jwt-encoded-state

**Comment by iphoneintosh** [comment]
@panva We added examples of the secure use of postMessage in OAuth. We are happy for any feedback.

**Comment by CheariX** [comment]
Can we do anything else to push this further?

**Review by danielfett — APPROVED** [review]

**Comment by danielfett** [comment]
Thank you for providing the PR, it will be included in the next published version.

**Pull request merged**
